### ISSUE TITLE
please give me my setrpc back taterontop#3980

### ISSUE THREAD

**Issue by taterontop** [PauprogamerZ/tater-bot-issues#1]
plz i want it back

**Comment by PauprogamerZ** [comment]
Ping a message on #announcements on Tater Central(https://discord.gg/74kpg2Ddyy) with the following message please as now the rpc is for the Github issues thing.

For suggestions or bug fixes please refer to https://github.com/PauprogamerZ/tater-bot-issues/issues

**Comment by PauprogamerZ** [comment]
Or something similar.

**Comment by PauprogamerZ** [comment]
Fixed
